<?php
/*
MoneySound
client.inc: ’è”E‹¤’ÊŠÖ”‚ð’è‹`‚·‚é
Copyright (C) 2012-2015 OFFICE OUTERGUY. All rights reserved.
mailto:contact@beatrek.com
Dual-licensed under the Apache License 2.0 and Beatrek Origin License.
*/

define("ENV_FILE_DIR_CLIENT", "./client/");
define("ENV_FILE_TEMPLATE_HTML", "template.html");
define("ENV_FILE_TEMPLATE_JS", "template.js");

define("ENV_PRODUCT_FAMILY_VERSION", "4.0");

?>
