<?php
/*
client.inc: 定数・共通関数を定義する
Copyright (C) 2008-2015 OFFICE OUTERGUY. All rights reserved.
mailto:contact@beatrek.com
Dual-licensed under the Apache License 2.0 and Beatrek Origin License.
*/

define("ENV_FILE_DIR_CLIENT", "./client/");

define("ENV_FILE_TEMPLATE_HTML", "template.html");
define("ENV_FILE_TEMPLATE_JS", "template.js");
define("ENV_FILE_TEMPLATE_PDF", "pdf.dat");

define("ENV_PRODUCT_CLIENT_VERSION", "5.3");

?>
